const freeLibrary = [
  {
    name: "Advanced Java",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "3hrs",
    lang: "Tamil",
  },
  {
    name: "Advanced Java",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "3hrs",
    lang: "English",
  },
  {
    name: "Advanced Java",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "3hrs",
    lang: "Hindi",
  },
  {
    name: "Algebra",
    image: "https://static.guvi.in/course-thumbnail/webps/datastructure.webp",
    hours: "17hrs",
    lang: "Tamil",
  },
  {
    name: "Algebra",
    image: "https://static.guvi.in/course-thumbnail/webps/datastructure.webp",
    hours: "17hrs",
    lang: "English",
  },
  {
    name: "Angular JS",
    image: "https://static.guvi.in/course-thumbnail/webps/angularjs.webp",
    hours: "1hrs",
    lang: "Tamil",
  },
  {
    name: "Angular JS",
    image: "https://static.guvi.in/course-thumbnail/webps/angularjs.webp",
    hours: "1hrs",
    lang: "English",
  },
  {
    name: "Angular JS",
    image: "https://static.guvi.in/course-thumbnail/webps/angularjs.webp",
    hours: "1hrs",
    lang: "English",
  },
  {
    name: "Binary Tree Traversal",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "6hrs",
    lang: "Tamil",
  },
  {
    name: "Binary Tree Traversal",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "6hrs",
    lang: "English",
  },
  {
    name: "Binary Tree Traversal",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "6hrs",
    lang: "Hindi",
  },
  {
    name: "Binary Tree Traversal for Beginners",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "3hrs",
    lang: "Tamil",
  },
  {
    name: "Binary Tree Traversal for Beginners",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "3hrs",
    lang: "English",
  },
  {
    name: "Binary Tree Traversal for Beginners",
    image: "https://static.guvi.in/course-thumbnail/webps/java.webp",
    hours: "3hrs",
    lang: "Hindi",
  },
  {
    name: "Bootstrap 3",
    image: "https://static.guvi.in/course-thumbnail/webps/bootstrap.webp",
    hours: "3hrs",
    lang: "Tamil",
  },
  {
    name: "Bootstrap 3",
    image: "https://static.guvi.in/course-thumbnail/webps/bootstrap.webp",
    hours: "3hrs",
    lang: "English",
  },
  {
    name: "Bootstrap 3",
    image: "https://static.guvi.in/course-thumbnail/webps/bootstrap.webp",
    hours: "3hrs",
    lang: "Hindi",
  },
  {
    name: "C",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "5hrs",
    lang: "Tamil",
  },
  {
    name: "C",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "5hrs",
    lang: "English",
  },
  {
    name: "C",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "5hrs",
    lang: "Hindi",
  },
  {
    name: "C",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "1hrs",
    lang: "Tamil",
  },
  {
    name: "C",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "1hrs",
    lang: "English",
  },
  {
    name: "C",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "1hrs",
    lang: "Hindi",
  },
  {
    name: "C Advanced",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "1hrs",
    lang: "Tamil",
  },
  {
    name: "C Advanced",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "1hrs",
    lang: "English",
  },
  {
    name: "C Advanced",
    image: "https://static.guvi.in/course-thumbnail/webps/c.webp",
    hours: "1hrs",
    lang: "Hindi",
  },
];
export default freeLibrary;
